// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEKXdhoDY0zijJAyVlCMlMrkUbUdM3tPc',
    appId: '1:787923055628:web:dff26cc16ff4ce447f2a29',
    messagingSenderId: '787923055628',
    projectId: 'dobha-live',
    authDomain: 'dobha-live.firebaseapp.com',
    storageBucket: 'dobha-live.firebasestorage.app',
    measurementId: 'G-2LP19HP4P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0j5paCdUVTYpZfmdKBgwVjuuj5OQrL4',
    appId: '1:787923055628:android:4e2787b23f9f600c7f2a29',
    messagingSenderId: '787923055628',
    projectId: 'dobha-live',
    storageBucket: 'dobha-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC87FkhZTwJcOvrWC8bCaUzlse_dUV6DfU',
    appId: '1:787923055628:ios:6a3ed8076e739d1b7f2a29',
    messagingSenderId: '787923055628',
    projectId: 'dobha-live',
    storageBucket: 'dobha-live.firebasestorage.app',
    androidClientId: '787923055628-hsnaoce0e7boo6at9puvjm028trmudog.apps.googleusercontent.com',
    iosClientId: '787923055628-gm7j2ss8g15o30drcdmls7ugsh2t22vq.apps.googleusercontent.com',
    iosBundleId: 'com.dobhadobha.dobhaLive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEKXdhoDY0zijJAyVlCMlMrkUbUdM3tPc',
    appId: '1:787923055628:web:d9a49f327cc5763e7f2a29',
    messagingSenderId: '787923055628',
    projectId: 'dobha-live',
    authDomain: 'dobha-live.firebaseapp.com',
    storageBucket: 'dobha-live.firebasestorage.app',
    measurementId: 'G-EYGNQ1YX3E',
  );
}
